service: seanmclambda
app: seanmclambda

provider:
  name: aws
  runtime: python3.8

functions:
  seanmcgold:
    handler: handler.broadcast_seanmcgold
    description: Run seanmcgold
    events:
      - schedule: rate(2 hours)
      - schedule: cron(0 12 * * ? *)
      - cloudwatchLog:
          logGroup: '/aws/lambda/seanmclambda'
    environment:
      SEANMCAPP_KEY: ${param:SEANMCAPP_KEY}
      SEANMCGOLD_SUBSCRIBER: ${param:SEANMCGOLD_SUBSCRIBER}
