org: redhoyasa
service: seanmclambda
app: seanmclambda

provider:
  name: aws
  runtime: python3.8

functions:
  seanmcgold:
    handler: handler.broadcast_seanmcgold
    description: Run seanmcgold
    events:
      - schedule: cron(0 14 * * MON-FRI *)
      - cloudwatchLog:
          logGroup: '/aws/lambda/seanmclambda-seanmcgold'
    environment:
      SEANMCAPP_KEY: ${param:SEANMCAPP_KEY}
      SEANMCGOLD_SUBSCRIBER: ${param:SEANMCGOLD_SUBSCRIBER}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
