service: seanmclambda
app: seanmclambda

provider:
  name: aws
  runtime: python3.8

functions:
  seanmcgold:
    handler: handler.broadcast_seanmcgold
    description: Run seanmcgold
    events:
      - schedule:
          rate: cron(0 18 * * *)
          enabled: true
      - schedule:
          rate: rate(2 hours)
          enabled: false
      - cloudwatchLog:
          logGroup: '/aws/lambda/seanmclambda'
    environment:
      SEANMCAPP_KEY: ${param:SEANMCAPP_KEY}
      SEANMCGOLD_SUBSCRIBER: ${param:SEANMCGOLD_SUBSCRIBER}
